language: shell
dist: bionic
services: docker

jobs:
  include:
    - stage: "build"
      name: "opencv 3.4.x fedora"
      script:
        - make build CV=3.4 DIST=fedora
        - make push CV=3.4 DIST=fedora
    - script:
      - make build CV=4.4 DIST=fedora
      - docker tag dkimg/opencv:4.4 dkimg/opencv:latest
      - make push CV=4.4 DIST=fedora
      - make push CV=latest DIST=fedora
      name: "opencv 4.4.x fedora"
    - script:
      - make build CV=3.4 DIST=alpine
      - make push CV=3.4 DIST=alpine
      name: "opencv 3.4.x alpine"
    - script:
      - make build CV=4.4 DIST=alpine
      - make push CV=4.4 DIST=alpine
      name: "opencv 4.4.x alpine"
    - stage: "test"
      name: "opencv 3.4.x fedora"
      script: make test CV=3.4 DIST=fedora
    - script: make test CV=4.4 DIST=fedora
      name: "opencv 4.4.x fedora"
    - script: make test CV=3.4 DIST=alpine
      name: "opencv 3.4.x alpine"
    - script: make test CV=4.4 DIST=alpine
      name: "opencv 4.4.x alpine"