sudo: required

services:
  - docker

before_install:
  - docker pull devlogos/opencv:base

script:
  - docker build -t devlogos/opencv:3.3.1 ./3.3.1
  - docker build -t devlogos/opencv:3.4.1 ./3.4.1
