language: shell
dist: bionic
services: docker

#    - stage: "Tests"                # naming the Tests stage
#      name: "Unit Tests"            # names the first Tests stage job
#      script: ./unit-tests
#    - script: ./integration-tests
#      name: "Integration Tests"     # names the second Tests stage job

jobs:
  include:
    - stage: "build"
      name: "opencv 3.4.x"
      script: make build CV=3.4
    - script: make build CV=4.4
      name: "opencv 4.4.x"
    - stage: "push"
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag dkimg/opencv:4.4 dkimg/opencv:latest
        - make deploy CV=3.4
        - make deploy CV=4.4
        - make deploy CV=latest
    - stage: "test"
      script:
        - make test CV=3.4
        - make test CV=4.4