os: linux
dist: bionic
language: shell
services: docker

jobs:
  include:
    - stage: "Fedora"
      script:
        - make CV=4.4.0 DIST=fedora
        - make latest CV=4.4.0 DIST=fedora
    - script: make CV=4.3.0 DIST=fedora
    - script: make CV=3.4.11 DIST=fedora
    - script: make CV=3.4.10 DIST=fedora
    - stage: "Alpine"
      script: make CV=4.4.0 DIST=alpine
    - script: make CV=4.3.0 DIST=alpine
    - script: make CV=3.4.11 DIST=alpine
    - script: make CV=3.4.10 DIST=alpine
    - stage: "Ubuntu"
      script: make CV=4.4.0 DIST=ubuntu
    - script: make CV=4.3.0 DIST=ubuntu
    - script: make CV=3.4.11 DIST=ubuntu
    - script: make CV=3.4.10 DIST=ubuntu