language: shell
dist: bionic
services: docker

jobs:
  include:
    - stage: build opencv 3.4.x
      script: make build CV=3.4
    - stage: build opencv 4.4.x
      script: make build
    - stage: push
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag dkimg/opencv:4.4 dkimg/opencv:latest
        - make deploy CV=3.4
        - make deploy CV=4.4
        - make deploy CV=latest
    - stage: test
      script:
        - make test CV=3.4
        - make test CV=4.4