sudo: required

services:
  - docker

before_install:
  - docker pull devlogos/fedora-opencv:base

script:
  - docker build -t devlogos/fedora-opencv:3.3.1 ./3.3.1
  - docker build -t devlogos/fedora-opencv:3.4.1 ./3.4.1
