language: shell
dist: bionic
services: docker

jobs:
  include:
    - stage: "build"
      name: "opencv 3.4.x"
      script:
        - make build CV=3.4
        - make push CV=3.4
    - script:
      - make build CV=4.4
      - docker tag dkimg/opencv:4.4 dkimg/opencv:latest
      - make push CV=4.4
      - make push CV=latest
      name: "opencv 4.4.x"
    - stage: "test"
      name: "opencv 3.4.x"
      script: make test CV=3.4
    - script: make test CV=4.4
      name: "opencv 4.4.x"