name: Docker Image CI

on:
  push:
    branches: [ gh-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [4.5.4, 4.4.0, 4.3.0, 3.4.16]
        dist: ["debian", "fedora", "ubuntu"]
    steps:
      -
        uses: actions/checkout@v2
        name: Checkout code
      -
        name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      -
        name: Build
        run: make build CV=${{ matrix.version }} DIST=${{ matrix.dist }}
      -
        name: Test
        run: make test CV=${{ matrix.version }} DIST=${{ matrix.dist }}
      -
        name: Push
        run: make push CV=${{ matrix.version }} DIST=${{ matrix.dist }}
  latest:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        name: Checkout code
      -
        name: Latest
        run: make latest CV=4.5.4 DIST=fedora
